name: WordPress Theme CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install PHP dependencies
      run: composer install
      working-directory: ./jcubsa_theme

    - name: Install Node.js dependencies
      run: npm install
      working-directory: ./jcubsa_theme

    - name: Build assets
      run: npm run build
      working-directory: ./jcubsa_theme

    - name: Run PHP lint
      run: composer lint
      working-directory: ./jcubsa_theme

    - name: Run tests
      run: npm run test
      working-directory: ./jcubsa_theme

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Staging
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
      run: |
        ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no user@your-staging-server "cd /path-to-your-theme && git pull origin main && composer install && npm install && npm run build"
